// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqUZoNhaRsgtACR1tz5T3Qj1yZHHF1EfU',
    appId: '1:714183271369:web:69290e1ab17f2b7d407e18',
    messagingSenderId: '714183271369',
    projectId: 'razolabwork',
    authDomain: 'razolabwork.firebaseapp.com',
    storageBucket: 'razolabwork.appspot.com',
    measurementId: 'G-SEP9GY14R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzuVwvrlaFPAWTQssQodymgEeO26KBVu8',
    appId: '1:714183271369:android:514274a8e49c8913407e18',
    messagingSenderId: '714183271369',
    projectId: 'razolabwork',
    storageBucket: 'razolabwork.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_NjB9-KcZmG80tHeq00fcyB_3b_aJ9mQ',
    appId: '1:714183271369:ios:fecfc06ff37d4b74407e18',
    messagingSenderId: '714183271369',
    projectId: 'razolabwork',
    storageBucket: 'razolabwork.appspot.com',
    iosBundleId: 'com.example.razoLabwork3c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_NjB9-KcZmG80tHeq00fcyB_3b_aJ9mQ',
    appId: '1:714183271369:ios:dc6415e6af6a7809407e18',
    messagingSenderId: '714183271369',
    projectId: 'razolabwork',
    storageBucket: 'razolabwork.appspot.com',
    iosBundleId: 'com.example.razoLabwork3c.RunnerTests',
  );
}
